const FLAGS: Record<string, string> = {
  Argentina: '🇦🇷',
  Australia: '🇦🇺',
  Austria: '🇦🇹',
  Belgium: '🇧🇪',
  Brazil: '🇧🇷',
  Canada: '🇨🇦',
  'Cape Verde Islands': '🇨🇻',
  Colombia: '🇨🇴',
  'Congo DR': '🇨🇩',
  Croatia: '🇭🇷',
  Egypt: '🇪🇬',
  England: '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
  France: '🇫🇷',
  Germany: '🇩🇪',
  Ghana: '🇬🇭',
  Iran: '🇮🇷',
  'Ivory Coast': '🇨🇮',
  Japan: '🇯🇵',
  Mexico: '🇲🇽',
  Morocco: '🇲🇦',
  Netherlands: '🇳🇱',
  Norway: '🇳🇴',
  Paraguay: '🇵🇾',
  Poland: '🇵🇱',
  Portugal: '🇵🇹',
  Senegal: '🇸🇳',
  'South Africa': '🇿🇦',
  'South Korea': '🇰🇷',
  Spain: '🇪🇸',
  Sweden: '🇸🇪',
  Switzerland: '🇨🇭',
  Tunisia: '🇹🇳',
  Turkey: '🇹🇷',
  'United States': '🇺🇸',
  Uruguay: '🇺🇾',
  Ecuador: '🇪🇨',
  Algeria: '🇩🇿',
  'Saudi Arabia': '🇸🇦',
  'New Zealand': '🇳🇿',
  'Bosnia-Herzegovina': '🇧🇦',
  'Curaçao': '🇨🇼',
  'Czechia': '🇨🇿',
  Haiti: '🇭🇹',
  Iraq: '🇮🇷',
  Jordan: '🇯🇴',
  Panama: '🇵🇦',
  Scotland: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
  Uzbekistan: '🇺🇿',
}

export function getFlag(teamName: string): string {
  return FLAGS[teamName] || '🏳️'
}
